[pytest]
testpaths = test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --tb=short
    --cov=entities
    --cov=user_cases
    --cov=infraestrutura
    --cov=llm
    --cov-report=term-missing
    --cov-report=html:htmlcov

[coverage:run]
omit =
    test/*
    worker/*